""" post delit cascade coment

Revision ID: 11b248b5c1a1
Revises: 207efc700e14
Create Date: 2023-04-21 18:55:30.355012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b248b5c1a1'
down_revision = '207efc700e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_post_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post'], ['post_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_post_fkey', 'posts', ['post'], ['post_id'])

    # ### end Alembic commands ###
