"""add post and coment

Revision ID: 207efc700e14
Revises: 8c275b725162
Create Date: 2023-04-21 11:02:36.026072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207efc700e14'
down_revision = '8c275b725162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('autor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('autor', sa.Integer(), nullable=True),
    sa.Column('post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post'], ['posts.post_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    # ### end Alembic commands ###
